config/routes.rb
TrackddApp::Application.routes.draw do
  resources :authentications, :branches

  devise_for :users, :path => 'accounts', :controllers => {:registrations => 'registrations'}

  resources :goods

  resources :shipments

  root :to => "Dashboard#show"
  match '/dashboard' => 'dashboard#show'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'Dashboard#show'
  match '/shipment/find_member' => 'shipments#find_member'
  match '/shipment/find_book' => 'shipments#find_book'
  match 'shipments_search' => 'shipments#search'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    if params[:current_branch].blank?
      user_session['current_branch'] = Branch.branch_from_subdomain(current_user.subdomain)
    else
      user_session['current_branch'] = Branch.find(params[:current_branch].to_i)
    end
    @associate_branches = Branch.associate_branches(current_user.subdomain)
  end
end

app/views/dashboard/show.html.erb
<%= javascript_tag :defer => 'defer' do -%>
	$('#current_branch').html('<%= user_session['current_branch'].name %>');
<% end -%>

<div class='notice'>
	You are a staff of <b><%= Branch.branch_name_from_subdomain(current_user.subdomain) %>.</b>
	If this is not correct, call tech support.
	<br/>
	You are currently logged into <%= user_session['current_branch'].name %>. 
	<% if  @associate_branches.length > 1 -%>
		<hr/>
		Click on any of the following branches to change your current branch.
		<br/>
		<ol>
			<% @associate_branches.each do |b| -%>
				<li><%= link_to b.name, dashboard_path(:current_branch => b.id), :confirm => "Are you sure you want to change the branch to #{b.name}?" %></li>
			<% end -%>
		</ol>
	<% end -%>		
</div>

<% if current_user.frontoffice? -%>
<div class='alert'>
	You logged in with <%= current_user.email %>, instead use the id that was created for you.
</div>
<% end -%>


	<div class='span-24'>
		<% if current_user.strata_employee? %>
			<div class='span-24'>
				
      </div>
      
		<% end -%>
    <div class='span-24'>
      <div class='span-1 menu-button menu-color'>
        <div class='menu-icon'>
          
            <%= link_to :controller => 'shipments', :action => 'new'  do -%>
              <%= image_tag 'consignment.png' %>
            <% end -%>
            
        </div>
        <div class='span-1 menu-text'>
          Door Delivery
        </div>
      </div>
    </div>
      
    
	</div>