config/routes.rb
TrackddApp::Application.routes.draw do
  resources :authentications, :branches

  devise_for :users, :path => 'accounts', :controllers => {:registrations => 'registrations'}

  resources :goods

  resources :shipments

  root :to => "Dashboard#show"
  match '/dashboard' => 'dashboard#show'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'Dashboard#show'
  match '/shipment/find_member' => 'shipments#find_member'
  match '/shipment/find_book' => 'shipments#find_book'
  match 'shipments_search' => 'shipments#search'

end

app/models/good.rb
class Good < ActiveRecord::Base
  include ActiveRecord::Transitions
  belongs_to :book, :class_name => 'Book', :foreign_key => 'book_no'
  belongs_to :shipment
  attr_accessible :book_no, :action, :state, :book_no_str
  attr_accessor :title, :event
  validates :book_no, :presence => true, :uniqueness => {:scope => :shipment_id}, :length => { :maximum => 30 }
  validate :book_exists

  state_machine do
  	state :New # first one is the initial state
    state :Confirmed

		event :confirm do
			transitions :to => :Confirmed, :from => :new
		end
	end 
  
  def book_exists
    book = Book.find(self.book_no)
    if book.nil?
	    errors.add(:book_no, ' does not exists')
    end
    rescue ActiveRecord::RecordNotFound
      errors.add(:book_no, ' does not exists')
  end
  
  def book_title
    book = Book.find(self.book_no)
    Title.find(book.title_id).title
  end
  
  def curr_state
    cstate = ''
    case 
      when  self.state.eql?('New')
        cstate = 'pending'
      when  self.state.eql?('Confirmed')
        cstate = 'confirmed'
    end
    
    return cstate
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  # GET /goods
  # GET /goods.xml
  def index
    @goods = Goods.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @goods }
    end
  end

  # GET /goods/1
  # GET /goods/1.xml
  def show
    @good = Goods.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @good }
    end
  end

  # GET /goods/new
  # GET /goods/new.xml
  def new
    @good = Goods.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @good }
    end
  end

  # GET /goods/1/edit
  def edit
    @good = Goods.find(params[:id])
  end

  # POST /goods
  # POST /goods.xml
  def create
    @good = Goods.new(params[:good])

    respond_to do |format|
      if @good.save
        format.html { redirect_to(@good, :notice => 'Goods was successfully created.') }
        format.xml  { render :xml => @good, :status => :created, :location => @good }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @good.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /goods/1
  # PUT /goods/1.xml
  def update
    @good = Goods.find(params[:id])

    respond_to do |format|
      if @good.update_attributes(params[:good])
        format.html { redirect_to(@good, :notice => 'Goods was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @good.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.xml
  def destroy
    @good = Goods.find(params[:id])
    @good.destroy

    respond_to do |format|
      format.html { redirect_to(goods_index_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_form.html.erb
<%= form_for(@good) do |f| %>
  <% if @good.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good.errors.count, "error") %> prohibited this good from being saved:</h2>

      <ul>
      <% @good.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goods/edit.html.erb
<h1>Editing good</h1>

<%= render 'form' %>

<%= link_to 'Show', @good %> |
<%= link_to 'Back', goods_index_path %>

app/views/goods/index.html.erb
<h1>Listing goods</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @goods.each do |good| %>
  <tr>
    <td><%= link_to 'Show', good %></td>
    <td><%= link_to 'Edit', edit_good_path(good) %></td>
    <td><%= link_to 'Destroy', good, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Goods', new_good_path %>

app/views/goods/new.html.erb
<h1>New good</h1>

<%= render 'form' %>

<%= link_to 'Back', goods_index_path %>

app/views/goods/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_good_path(@good) %> |
<%= link_to 'Back', goods_index_path %>