config/routes.rb
TrackddApp::Application.routes.draw do
  resources :authentications, :branches

  devise_for :users, :path => 'accounts', :controllers => {:registrations => 'registrations'}

  resources :goods

  resources :shipments

  root :to => "Dashboard#show"
  match '/dashboard' => 'dashboard#show'
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'Dashboard#show'
  match '/shipment/find_member' => 'shipments#find_member'
  match '/shipment/find_book' => 'shipments#find_book'
  match 'shipments_search' => 'shipments#search'

end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
	include ActiveRecord::Transitions
  ACTION = {
    :Exchange   => 'Exchange',
    :Deliver  => 'Deliver', 
    :Pickup   => 'Pickup'
  }  
  
  has_many :goods, :dependent => :destroy
	accepts_nested_attributes_for :goods, :allow_destroy => :true, :reject_if => lambda { |a| a[:book_no].blank? }
  belongs_to :member, :class_name => 'Membership', :foreign_key => 'membership_id'
  belongs_to :origin, :class_name => 'Branch', :foreign_key => 'origin_id'
  attr_accessible :origin_id, :destination, :goods_attributes, :special_instr, :action, :card_id, :change_addr,:state
  validate :card_exists

  before_save :set_member
  validates :card_id, :presence => true, :length => { :maximum => 30 }
  validates :destination, :presence => true, :length => { :maximum => 500 }
  validate :card_exists
	state_machine do
  	state :New # first one is the initial state
  	state :Initiated
  	state :Confirmed
  	state :Cancelled

		event :initiate do
			transitions :to => :Initiated, :from => :New
		end
		event :confirm do
			transitions :to => :Confirmed, :from => :Initiated
		end
		event :cancel do
			transitions :to => :Cancelled, :from => [:New, :Initiated]
		end
	end 
  def set_member
    member = Membership.find_by_card_id(self.card_id)
    self.membership_id = member.id
  end
  def card_exists
    member = Membership.find_by_card_id(self.card_id)
    if member.nil?
	    errors.add(:card_id, ' does not exists')
    end

  end
  
  def self.search(params, start_d_s, end_d_s)
    created = params[:Created]
    branch_id = params[:branch_id]
    start_date = Time.zone.today.beginning_of_day
    end_date =  Time.zone.today.end_of_day
    case 
      when created.eql?('Today')
        start_date = Time.zone.today.beginning_of_day
        end_date =  Time.zone.today.end_of_day
      when created.eql?('Range')
        start_date = start_d_s.to_time.beginning_of_day
        end_date =  end_d_s.to_time.beginning_of_day
      when created.eql?('On')
        start_date = start_d_s.to_time.beginning_of_day
        end_date =  start_d_s.to_time.end_of_day
    end
    ship = nil
    
    if (branch_id.eql?('0') ) then
      if created.eql?('All') then 
        ship = Shipment.find(:all, :order => ' id DESC').paginate(:page => params[:page], :per_page => 10)
      else
        ship =  Shipment.find(:all, :conditions => [' created_at >= ? and created_at <= ? ', 
        start_date, end_date], :order => ' id DESC').paginate(:page => params[:page], :per_page => 10)
      end
    elsif
      if created.eql?('All') then 
        ship = Shipment.find(:all, :conditions => ['origin_id = ? ', branch_id],:order => ' id DESC').paginate(:page => params[:page], :per_page => 10)
        
      else
        ship = Shipment.find(:all, :conditions => [' origin_id = ? and created_at >= ? and created_at <= ? ', 
        branch_id, start_date, end_date], :order => ' id DESC').paginate(:page => params[:page], :per_page => 10)
        
      end
    end
    return ship
  end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  # GET /shipments
  # GET /shipments.xml
  def index
    @shipments = Shipment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shipments }
    end
  end

  def search
    start_d_s = params[:start]
    end_d_s = params[:end]
    start_s = ""
    end_s = ""
    
    if (!start_d_s.nil?)
      start_s = start_d_s["start(3i)"] + '-' + start_d_s["start(2i)"] +'-'+ start_d_s["start(1i)"]
    end
    if (!end_d_s.nil?)
      end_s = end_d_s["end(3i)"] + '-' + end_d_s["end(2i)"] +'-'+ end_d_s["end(1i)"]
    end
    @shipments = Shipment.search(params, start_s, end_s)
    render 'search'
  end

  # GET /shipments/1
  # GET /shipments/1.xml
  def show
    @shipment = Shipment.find(params[:id])
    @goods_to_deliver =  Good.find_all_by_shipment_id_and_action(@shipment.id, 'Deliver')
    @goods_to_pickup =  Good.find_all_by_shipment_id_and_action(@shipment.id, 'Pickup')
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shipment }
    end
  end

  # GET /shipments/new
  # GET /shipments/new.xml
  def new
    @shipment = Shipment.new
    5.times { @shipment.goods.build }


    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shipment }
    end
  end

  # GET /shipments/1/edit
  def edit
    @shipment = Shipment.find(params[:id])
  end

  # POST /shipments
  # POST /shipments.xml
  def create
    @shipment = Shipment.new(params[:shipment])
    respond_to do |format|
      if @shipment.save
        format.html { redirect_to(@shipment, :notice => 'Shipment was successfully created.') }
        format.xml  { render :xml => @shipment, :status => :created, :location => @shipment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shipment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shipments/1
  # PUT /shipments/1.xml
  def update
    @shipment = Shipment.find(params[:id])

    respond_to do |format|
      if @shipment.update_attributes(params[:shipment])
        format.html { redirect_to(@shipment, :notice => 'Shipment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shipment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shipments/1
  # DELETE /shipments/1.xml
  def destroy
    @shipment = Shipment.find(params[:id])
    @shipment.destroy

    respond_to do |format|
      format.html { redirect_to(shipments_url) }
      format.xml  { head :ok }
    end
  end
  
  def find_member
    @member = Membership.find_by_card_id(params[:card])
    render 'find_member', :layout => false
  end
  
  def find_book
    @book = Book.find(params[:book_no])
    @col_name = params[:col_name]
    render 'find_book', :layout => false
  end

end

app/helpers/shipments_helper.rb
module ShipmentsHelper
  def report_msg(create, start_d_s, end_d_s)
    mesg = ""
    if (!start_d_s.nil?)
      start_s = start_d_s["start(3i)"] + '-' + start_d_s["start(2i)"] +'-'+ start_d_s["start(1i)"]
    end
    if (!end_d_s.nil?)
      end_s = end_d_s["end(3i)"] + '-' + end_d_s["end(2i)"] +'-'+ end_d_s["end(1i)"]
    end
    case
    when create.eql?("All") then mesg = " till now "
    when create.eql?("On") then mesg = " raised on "+start_s
    when create.eql?("Today") then mesg = "raised today"
    when create.eql?("Range") then mesg = "raised between "+ start_s+" and "+end_s
    end
  end
end

app/views/shipments/_edit_form.html.erb
<%= javascript_tag :defer => 'defer' do -%>
	$(document).ready(function () {
		ShipmentApp.initForm('Exchange', true);
	});
<% end -%>
<div class=span-14>
<%= form_for(@shipment)  do |f| %>
  <% if @shipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
      <% @shipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="span-14 heading">
			Confirm delivery/pickup
		</div>

		<br/>
		<div class="span-14">
			<table class='form'>
        <tr>
          <td colspan="6">					
            <%= @shipment.action %>
          </td>
        </tr>

				<tr><td colspan="2"><%= f.label :Branch %></td><td colspan="4"><%= @shipment.origin.name %></td></tr>
				<tr><td colspan="2"><%= f.label 'Card No' %></td>
            <td colspan="1"><%= @shipment.card_id  %></td> 
            <td colspan="2"><%= @shipment.member.member %> 
            <td colspan="1"><%= @shipment.member.phone  %></td>
        </tr>
        
				<tr><td colspan="2"><%= f.label 'Address' %></td>
            <!--td colspan="1"><%= f.check_box :change_addr, {:readonly=>'true'}, 'Y', 'N' %></td-->
            <td colspan="4"><%= @shipment.destination %></td>
        </tr>
				<tr><td colspan="2"><%= f.label 'Special Intructions' %></td>
            <td colspan="4"><%= @shipment.special_instr %>
            <%= f.hidden_field :state, :value=> :Initiated %></td>
        </tr>
			</table>
      <h3>Update delivery/pickup status</h3>
		</div>
    <div class="span-14">
      <table class="form">
        <tr>
          <th colspan="1">Book</th>
          <th colspan="3">Title </th>
          <th colspan="1">Request</th>
          <th colspan="1">Confirmed?</th>
          
          
        </tr>

        <%= f.fields_for :goods do |builder| -%>
					<%= render 'edit_good_field', :f => builder %>
				<% end -%>
			</table>
		</div>

  
  <div class="span-14 actions">
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/shipments/_edit_good_field.html.erb
<tr>
  <td colspan="1"><%= f.text_field :book_no_str, :class=>'readonly',:readonly=>'true', :maxlength=>10 %></td>
  <td colspan="3"><%= f.text_field :book_title, :class=>'readonly',:readonly=>'true' %> </td>
  <td colspan="1"><%= f.text_field :action, :class=>'readonly',:readonly=>'true', :maxlength=>10 %> </td>
  <td colspan="1"><%= f.hidden_field :book_no, :maxlength=>15 %>
      <%= f.check_box :state, { }, 'Confirmed', 'New' %></td>
  </td>
  
</tr>

app/views/shipments/_form.html.erb
<%= javascript_tag :defer => 'defer' do -%>
	$(document).ready(function () {
		ShipmentApp.initForm('Exchange', true);
	});
<% end -%>
<div class="span-14">
<%= form_for(@shipment)  do |f| %>
  <% if @shipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
      <% @shipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  	<div class="span-14 heading">
			Enter delivery/pickup details
		</div>
		<br/>
		<div class="span-17">
			<table class='form'>
        <tr>
          <td colspan="6">					
            Exchange <%= f.radio_button :action, Shipment::ACTION[:Exchange], {:checked => true} %>
               Deliver <%= f.radio_button :action, Shipment::ACTION[:Deliver] %>
            Pick up<%= f.radio_button :action, Shipment::ACTION[:Pickup] %>
          </td>
        </tr>

				<tr><td colspan="2"><%= f.label :Branch %></td><td colspan="4"><%= f.collection_select :origin_id, Branch.all, :id, :name %></td></tr>
				<tr><td colspan="2"><%= f.label 'Card No' %></td>
            <td colspan="1"><%= f.text_field :card_id , :maxlength => 15 %></td> 
            <td colspan="2"><%= text_field_tag :mem_name, '', :class=>'readonly',:readonly=>'true' %> 
            <td colspan="1"><%= text_field_tag :mem_phone, '', :class=>'readonly',:readonly=>'true' %></td>
        </tr>
        
				<tr><td colspan="2"><%= f.label 'Change address' %></td>
            <td colspan="4"><%= f.check_box :change_addr, {:checked => 'unchecked'}, 'Y', 'N' %></td>
        <tr>
            <td colspan="2"><br/></td> 
            <td colspan="4"><%= f.text_area :destination, :maxlength => 500, :size => "15x3" ,:placeholder => 'click change the default address', :readonly=> 'true' %></td>
        </tr>
				<tr><td colspan="2"><%= f.label 'Special Intructions' %></td><td colspan="4"><%= f.text_area :special_instr, :maxlength => 250, :size => "15x3" ,:placeholder => 'specific time to pickup/deliver'%></td></tr>
			</table>
		</div>
		<div class="span-7" id="div_deliver_goods">
			<table id='goods_table' class='form'>
				<tr><th>Books to deliver</th><th></th></tr>
				<%= f.fields_for :goods do |builder| -%>
					<%= render 'good_deliver', :f => builder %>
				<% end -%>
			</table>
		</div>
    <div class="span-14" id="destination_div"  style="display:none">
      <%= text_field_tag :mem_addr %>
      <%= text_field_tag :mem_phone_hid %>
      <%= text_field_tag :mem_name_hid %>

    </div>
    <div class="span-14" id="title_div"  style="display:none">
    </div>
    <div class="span-7" id="div_pickup_goods">
			<table id='goods_table' class='form'>
				<tr><th>Books to pickup</th><th></th></tr>
				<%= f.fields_for :goods do |builder| -%>
					<%= render 'good_pickup', :f => builder %>
				<% end -%>
			</table>
		</div>

  
  <div class="span-14 actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/shipments/_good_deliver.html.erb
<tr>
  <td><%= f.text_field :book_no_str ,:maxlength => 15 ,:placeholder => 'Prefix "B"...', :onChange => 'ShipmentApp.book_str(this);' %></td>
  <td><%= f.text_field :title, :class=>'readonly',:readonly=>'true' %> </td>
  
  <td><%= f.hidden_field :action ,:value=>'Deliver' %></td>
  <td><%= f.hidden_field :book_no %></td>
  <td><%= f.hidden_field :state ,:value=>'New' %></td>
</tr>

app/views/shipments/_good_pickup.html.erb
<tr>
	<td><%= f.text_field :book_no_str ,:maxlength => 15 ,:placeholder => 'Prefix "B"...', :onChange => 'ShipmentApp.book_str(this);' %></td>
  <td><%= f.text_field :title, :class=>'readonly',:readonly=>'true' %> </td>
  <td><%= f.hidden_field :action ,:value=>'Pickup' %></td>
  <td><%= f.hidden_field :book_no %></td>
  <td><%= f.hidden_field :state ,:value=>'New' %></td>

</tr>

app/views/shipments/_menu.html.erb
<div class="span-4 colborder">
	<div class="span-4">
		<p></p>
    <p>Door Delivery</p>
    <!--p><%= link_to 'Index', shipments_path %></p-->
    <p><%= link_to 'New', new_shipment_path %></p>
    <p><%= link_to "Search", shipments_search_path %>	</p>
	</div>
	<hr/>
	<div class="span-4">
		<p></p>
		<p><%= link_to "Home", root_path %>	</p>
    <p><%= link_to "Back", :back %> </p>
	</div>	
</div>

app/views/shipments/_searchForm.html.erb
<%= javascript_tag :defer => 'defer' do -%>
	$(document).ready(function () {
		ShipmentApp.initStatForm('<%= params[:Created] %>', true);
	});
<% end -%>

  <div class="span-14">
    <%= form_tag shipments_search_path, :class=>'shipmentStat', :method => 'get' do -%>
        <%= field_set_tag 'Search' do %>
          <div class="span-14">
          <%= label_tag 'Show Shipments:'%>
          <%= select_tag :Created, options_for_select([['All','All'],['Pickedup today','Today'],['Pickedup on','On'],['Pickedup Between','Range']], params[:Created]) %>
          <%= hidden_field_tag :report , params[:report] %>
          </div>
          <div class="span-7" id="div_start_date">
          <%= label_tag 'Start:'%>
          <%= date_select 'start', 'start', :order =>[:day, :month, :year] %>
          </div>
          <br/>
          <div class="span-7" id="div_end_date">
          <%= label_tag  'End  :'  %>
          <%= date_select :end, 'end', :order =>[:day, :month, :year] %>
          </div>
          <div class="span-14" id="div_from_branch">
          <%= label_tag  'Originating From  :'  %>
          <% if current_user.strata_employee? %>
            <%= select_tag :branch_id, options_for_select({ "All branches" => "0" })+ options_from_collection_for_select(Branch.all, :id, :name, params[:branch_id] )%>
          <% else %>
            <%= select_tag :branch_id1, options_for_select({ "All branches" => "0" })+ options_from_collection_for_select(Branch.all, :id, :name, params[:branch_id] ), :disabled => true %>
            <%= hidden_field_tag :branch_id , params[:branch_id] %>

            <%end%>
          </div>
          <br/>
          <div class="span-14">
          <%= submit_tag "Submit", :name => nil %>
          </div>
        <% end -%>
    <% end -%>
  </div>

app/views/shipments/edit.html.erb
<div class="span-24">
<div>
<%= render 'menu' %>
</div>
<div class="span=14">

<%= render 'edit_form' %>
</div>
</div>

app/views/shipments/find_book.html.erb
<%= text_field_tag :col_name_hid, @col_name %>
<%= text_field_tag :title_hid, @book.title.title %>

app/views/shipments/find_member.html.erb
<%= text_field_tag :mem_addr, @member.address %>
<%= text_field_tag :mem_phone_hid, @member.phone %>
<%= text_field_tag :mem_name_hid, @member.member %>

app/views/shipments/index.html.erb
<h1>Listing shipments</h1>

<table>
  <tr>
    <th>Card </th>
    <th>Action</th>
    <th>On</th>
  </tr>

<% @shipments.each do |shipment| %>
  <tr>
    <td><%= shipment.card_id %></td>
    <td><%= shipment.action %></td>
    <td><%= shipment.created_at.strftime('%d/%b/%Y %l:%M %p') %></td>
    <td><%= link_to 'Show', shipment %></td>
    <!--td><%= link_to 'Edit', edit_shipment_path(shipment) %></td -->
    <!--td><%= link_to 'Destroy', shipment, :confirm => 'Are you sure?', :method => :delete %></td-->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shipment', new_shipment_path %>

app/views/shipments/new.html.erb
<div class="span-24">
<div>
<%= render 'menu' %>
</div>
<div class="span=14">
<%= render 'form' %>
</div>
</div>

app/views/shipments/search.html.erb
<div class="span-24">
  <div>
    <%= render :partial => 'menu' %>
  </div>
  <div class="span-14">
    <%= render :partial => 'searchForm' %>
    <div class="span-14" >
    <% unless @shipments.size == 0 %>
      
      <h6>Shipments <%= report_msg(params[:Created], params[:start], params[:end]) %>
      </h6>
      <br/>
      <%= will_paginate(@shipments) %>

      <table>
        <tr>
          <th>No</th>
          <th>Card</th>
          <th>Member</th>
          <th>Request on</th>
        </tr>

        <% @shipments.each do |shipment| %>
        <tr>
          <td><%= shipment.id %></td>
          
          <td><%= shipment.card_id %></td>
          <td><%= shipment.member.member %></td>
          <td><%= shipment.created_at.strftime('%a, %d %B, %Y at %I:%M%p') %></td>
          
          
          <td><%= link_to 'Show', shipment %></td>
          <td><%= link_to 'Confirm', edit_shipment_path(shipment) %></td>
          <!--td><%= link_to 'Destroy', shipment, :confirm => 'Are you sure?', :method => :delete %></td-->
        </tr>
        <% end %>
      </table>
      
    <% end %>
    <% if @shipments.size == 0 %>

      <div class="span-11">
        <br/>
        no data found
      </div>  
    <% end %>
    </div>
  </div>
</div>

app/views/shipments/show.html.erb
<script type="text/javascript">
  function setPrinterDiv(id){
    document.getElementById(id).style.display = 'block';
    $('#print_div').printElement({
      overrideElementCSS:['print.css', { href:'print.css', media:'print'}],
      leaveOpen:true,
      printMode:'popup'
    });
		document.getElementById(id).style.display = 'none';
  }
</script>
<div class=span-24">
  <div>
    <%= render 'menu' %>
  </div>
  <div class="span-14">
    <p></p>
    <div class="span-14 heading">
			Door Delivery/Pickup Receipt
		</div>

    <%= button_to_function 'Print', "setPrinterDiv('print_div');" %> 

    <p id="notice"><%= notice %></p>

    <div class='span-14' id="print_div">
      <table>
        <tr>
          <td colspan="2" ><b>Receipt No.</b></td><td colspan="3"> <%=@shipment.id%></td> 
          
        </tr>
        <tr>
          <td colspan="1" ><b>Member:</b></td><td colspan="4"> <%=@shipment.member.member%></td> 
        </tr>
        <tr>
          <td colspan="1"> <b>Card:</b></td><td colspan="4"><%=@shipment.card_id%></td>
        <tr>
        <tr><td colspan="5"><b>Address:</b></td></tr>
        <tr><td colspan="4"><%=@shipment.destination%></td> <tr>
        <tr><td colspan="1">Phone:</td><td colspan="4"><%=@shipment.member.phone%></td> <tr>
        <tr><td colspan="1"><b>Instruction:</b></td><td colspan="4"><%="None" if @shipment.special_instr.nil?%><%= @shipment.special_instr%></td> <tr>
      </table>
        <h3>
          <%= "Books to deilver" unless @goods_to_deliver.size==0 %>
        </h3>
      
      <table>
        <% @goods_to_deliver.each do |deliver| %>
          <tr>
            <td colspan="5"><b><%=deliver.book_no_str%></b></td>
          </tr>
          <tr>        
            <td colspan="5"><%=deliver.book.title.title%></td>
          </tr>
          
        <% end %>
      </table>
      <h3>
        <%= "Books to pickup" unless @goods_to_deliver.size==0 %>
      </h3>
      <table>

        <% @goods_to_pickup.each do |pickup| %>
          <tr>
            <td colspan="5"><b><%=pickup.book_no_str%></b></td> 
          </tr>
          <tr>
            <td colspan="5"><%=pickup.book.title.title%></td>
            
          </tr>
          
        <% end %>
      </table>

      <table>
        <tr>
          <th colspan="2">Record at:</th><td colspan="3"><%=@shipment.created_at.strftime('%d/%b/%Y %l:%M %p')%></td>
        </tr>
        <tr>
          <td colspan="1">By:</td><td colspan="4"><br/><hr/></td>
        </tr>
        <tr>
          <td colspan="5">For JustBooksClc <%=@shipment.origin.name%></td>
        </tr>

        <tr>
          <td colspan="2"><b>Member signature:</b></td><td colspan="3"><span align="bottom"><br/><hr/></td>
        </tr>
        <tr>
              <td colspan="1"><b>Comments:</b></td><td colspan="3"><br/><hr/></td>
        </tr>
      </table>
    </div>
  </div>
</div>